import Head from 'next/head';
import ListingsTemplate from '@components/templates/Listings/Listings';

export default function Listings() {
	return (
		<>
			<Head>
				<title>Listings</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <ListingsTemplate/>
		</>
	);
}