import Head from 'next/head';
import OffersTemplate from '@components/templates/Offers/Offers';

export default function Offers() {
	return (
		<>
			<Head>
				<title>Offers</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <OffersTemplate/>
		</>
	);
}