import Head from 'next/head';
import PaymentsTemplate from '@components/templates/Payments/Payments';

export default function Payments() {
	return (
		<>
			<Head>
				<title>Payments</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <PaymentsTemplate/>
		</>
	);
}