import Head from 'next/head';
import TargetsTemplate from '@components/templates/Targets/Targets';
export default function Targets() {
	return (
		<>
			<Head>
				<title>Targets</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <TargetsTemplate/>
		</>
	);
}